ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS usage_reset_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS quiz_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flashcard_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS enhance_count INT NOT NULL DEFAULT 0;
